### ISSUE TITLE
quotation highlighting doesn't handle contractions

### ISSUE THREAD

**Issue by mkaminsky** [Reyhn3/atom-plain-simple#1]
The regular expression that highlights quotations mishandles certain cases, such as contractions.  For example:

```
I don't know Bob's address.
```

will incorrectly have highlighting from the `t` to the `b`.

Modifying the regular expression at the end of `grammars/plain-simple.cson` for Citations to be

```
'match': '(?<!\\w)[“"\'].*?["”\'](?!\\w)'
```

seems to fix the issue.  It's based on the regex used by the vim-notes package for Vim (which uses regular expression negative look-around).

Thanks!

**Comment by Reyhn3** [comment]
You're absolutely right!
Great report, great solution! (: 
I just uploaded the fix.
Thanks!
