### ISSUE TITLE
Deprecated selector in `plain-simple\styles\plain-simple.less`

### ISSUE THREAD

**Issue by DFelten** [Reyhn3/atom-plain-simple#14]
In `plain-simple\styles\plain-simple.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .plainsimple-heading,
.text .plain .simple .plainsimple-heading` => `atom-text-editor.editor .syntax--plainsimple-heading,
.text .plain .simple .plainsimple-heading`

* `atom-text-editor::shadow .plainsimple-number,
.text .plain .simple .plainsimple-number` => `atom-text-editor.editor .syntax--plainsimple-number,
.text .plain .simple .plainsimple-number`

* `atom-text-editor::shadow .plainsimple-emphasize,
.text .plain .simple .plainsimple-emphasize` => `atom-text-editor.editor .syntax--plainsimple-emphasize,
.text .plain .simple .plainsimple-emphasize`

* `atom-text-editor::shadow .plainsimple-citation,
.text .plain .simple .plainsimple-citation` => `atom-text-editor.editor .plainsimple-citation,
.text .plain .simple .plainsimple-citation`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Reyhn3** [comment]
Fixed in `version 1.1`.
