### ISSUE TITLE
Minor Feature Idea: Highlight email addreses

### ISSUE THREAD

**Issue by rodw** [Reyhn3/atom-plain-simple#3]
Currently URLs such as:

`https://example.com/foo/bar`

are highlighted, but email addresses such as:

`foo@example.com`

or

`mailto:foo@example.com`

are not.  It seems like they should (and easily could) be.

For what it is worth, I do notice that `mailto://foo@example.com` is highlighted, but that's not the actual mailto format.

**Comment by Reyhn3** [comment]
Great suggestion!
This has been added in `version 1.1`.
